medical_warehouse:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '1234'
      port: 5432
      dbname: medical_db
      schema: public
  target: dev