version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - relationships:
              arguments: # Add this line
                to: ref('dim_channels')
                field: channel_key